### PR TITLE
Completed css-brochure-form exercise. - Rosemary Liu

### PR DESCRIPTION
**Pull request by rosemary-liu**
image

### CODE REVIEW

**Review by TimelikeClosure — CHANGES_REQUESTED** [review]
@rosemary-liu Please center the form on the page, as in the example screenshot:

---



---

**Comment by rosemary-liu** [comment]
image

**Review by TimelikeClosure — CHANGES_REQUESTED** [review]
Better, but the form itself looks like it still needs some adjustments to look more like the example:
- The labels should be indented from the left side of the form controls
- The placeholders should have a larger font size and have more spacing on the sides
- The form controls should have lighter borders
- The submit button background color should be redder

---

image

---

image

**Comment by rosemary-liu** [comment]
image

**Review by TimelikeClosure — APPROVED** [review]

**Pull request merged**
